name: Test TASKY

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Python syntax
      run: |
        python -m py_compile main.py
        python -m py_compile models.py
        python -m py_compile database.py
        python -m py_compile notifications.py
        python -m py_compile scheduler.py
        python -m py_compile build.py
        
    - name: Test imports
      run: |
        python -c "import PyQt6; print('PyQt6 imported successfully')"
        python -c "import win10toast; print('win10toast imported successfully')"
        python -c "import sqlite3; print('sqlite3 imported successfully')"
        
    - name: Test build script
      run: |
        python build.py --help || echo "Build script runs (help not implemented)"
        
    - name: Success message
      run: |
        echo "✅ All tests passed! TASKY is ready for GitHub Actions."
        echo "🚀 Next step: Create a release tag to trigger the build workflow."
